### ISSUE TITLE
Add new resources

### ISSUE THREAD

**Issue by Rishit-dagli** [Rishit-dagli/Python3-by-practice#12]
*Multiple PRs accepted*

## Definitions

**Blogs** - Use the [Blogs](https://github.com/Rishit-dagli/Python3-by-practice/tree/master/Blogs) directory to put in blogs strictly written by you. The blog content should be in the directory README file. You should follow the following directory structure-

```
Blogs
├── your-blog-name
|   └── README.md (Your blog)
|   └── accompanying-content
└── README.md
```

**EBooks** - [EBooks](https://github.com/Rishit-dagli/Python3-by-practice/tree/master/EBooks) that are publicly available and may or may not be written by the PR making the PR. Make sure to use the Book Title as the file name unaltered. You should use a `.epub` or a `.pdf` file for the book. If you are uploading multiple formats of the same book, follow this directory structure-

```
EBooks
├── book-name
|   └── book-name.pdf
|   └── book-name.epub
```

**Training Modules** - The directory [Training Modules](https://github.com/Rishit-dagli/Python3-by-practice/tree/master/Training%20Modules) aims to have questions and solutions for them in Python 3. Make a folder to propose a new problem among the existing folders or make a new folder in Training Modules. The README.md should have the problem statement and you should have a file called `solution.py` with the main code as a solution.

```
Training Modules
├── category
|   └── README.md (The problem)
|   └── solution.py
└── README.md
```

### Include Author name

You would be expected to include under the heading:

```
_Originally Contributed by [GitHub-Username](https://github.com/GitHub-Username)_
```

### Include buttons for accessibility
Include a `Run in Google Colab` and `View Source on GitHub` buttons

#### Example (taken from the [Linear Regression Notebook](https://github.com/Rishit-dagli/Python3-by-practice/blob/master/Machine%20Learning/sklearn%20examples/Linear%20Regression/Linear%20Regression%20.ipynb) in this repo)-

_Notebook orignially contributed by: [Aditya-1500](https://github.com/Aditya-1500)_

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github.com/Rishit-dagli/Python3-by-practice/blob/master/Machine%20Learning/sklearn%20examples/Linear%20Regression/Linear%20Regression%20.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/Rishit-dagli/Python3-by-practice/blob/master/Machine%20Learning/sklearn%20examples/Linear%20Regression/Linear%20Regression%20.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>

<br>
<br>
<br>

#### Code to generate buttons

```
<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github.com/Rishit-dagli/Python3-by-practice/blob/master/Machine%20Learning/sklearn%20examples/Logistic%20Regression/Logistic%20Regression.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/Rishit-dagli/Python3-by-practice/blob/master/Machine%20Learning/sklearn%20examples/Logistic%20Regression/Logistic%20Regression.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>
```
### Include a short intro

Below the above-mentioned notebook buttons, be sure to add a small intro showing what the notebook does.

### Include clear Dataset Credits

In the notebook, intro be sure to add clear credits to the dataset owner.

---

Once your PR is merged you will also be listed under [Contributors ✨](https://github.com/Rishit-dagli/Python3-by-practice#contributors-).

Follow the [Contributing Guide](https://github.com/Rishit-dagli/Python3-by-practice#wish-to-contribute-to-this-repository-sparkles) in the README and [CODE OF CONDUCT](https://github.com/Rishit-dagli/Python3-by-practice/blob/master/CODE_OF_CONDUCT.md) for this project while making a PR.

**Comment by ngutierrez31** [comment]
I'd like to add the ebook Think Python.
