### ISSUE TITLE
Create a Logistic Regression example with Scikit-Learn

### ISSUE THREAD

**Issue by Rishit-dagli** [Rishit-dagli/Python3-by-practice#46]
In #36 the [Pima Indian Diabetes Dataset](https://github.com/Rishit-dagli/Python3-by-practice/tree/master/Machine%20Learning/sklearn%20examples/Logistic%20Regression) as a sample Logistic Regression dataset was added by @Avinashshah099 . I am looking for contributors who could add a notebook with an aim to show how Logistic Regression works with `sklearn` to predict `Outcome`.

The notebook is expected to be placed under `Machine Learning/sklearn examples/Logistic Regression.ipynb`

### Include Author name

You would be expected to include under the heading:

```
_Originally Contributed by [GitHub-Username](https://github.com/GitHub-Username)_
```

### Include buttons for accessibility
Include a `Run in Google Colab` and `View Source on GitHub` buttons

#### Example (taken from the [Linear Regression Notebook](https://github.com/Rishit-dagli/Python3-by-practice/blob/master/Machine%20Learning/sklearn%20examples/Linear%20Regression/Linear%20Regression%20.ipynb) in this repo)-

_Notebook orignially contributed by: [Aditya-1500](https://github.com/Aditya-1500)_

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github.com/Rishit-dagli/Python3-by-practice/blob/master/Machine%20Learning/sklearn%20examples/Linear%20Regression/Linear%20Regression%20.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/Rishit-dagli/Python3-by-practice/blob/master/Machine%20Learning/sklearn%20examples/Linear%20Regression/Linear%20Regression%20.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>

<br>
<br>
<br>

#### Code to generate buttons

```
<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github.com/Rishit-dagli/Python3-by-practice/blob/master/Machine%20Learning/sklearn%20examples/Logistic%20Regression/Logistic%20Regression.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/Rishit-dagli/Python3-by-practice/blob/master/Machine%20Learning/sklearn%20examples/Logistic%20Regression/Logistic%20Regression.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>
```
### Include a short intro

Below the above-mentioned notebook buttons, be sure to add a small intro showing what the notebook does.

### Include clear Dataset Credits

In the notebook, intro be sure to add clear credits to the dataset owner.

**Comment by aditya9110** [comment]
@Rishit-dagli can I contribute my code as I have done already?

**Comment by Rishit-dagli** [comment]
> @Rishit-dagli can I contribute my code as I have done already?

@aditya9110 Sure, you can take up this issue

**Comment by Rishit-dagli** [comment]
> @Rishit-dagli can I contribute my code as I have done already?

@aditya9110 Sure, anyone is welcome to take up this issue!

**Comment by Avinashshah099** [comment]
Done, I have uploaded the Logistic regression example file
