### ISSUE TITLE
Intro to python Numpy

### ISSUE THREAD

**Issue by reddymahendra52** [Rishit-dagli/Python3-by-practice#85]
I can make training module on introduction to Numpy

**Comment by reddymahendra52** [comment]
Can you assign me the task??

**Comment by Rishit-dagli** [comment]
This a great idea, I was planning on doing something similar too, I could also add to your work! What I suggest you do is create a branch in your fork and create a draft PR called "Intro to Numpy examples", you can work in greater detail on it later. in this manner, I could monitor and also add on top of your work.

**Comment by reddymahendra52** [comment]
Is it okay?? i was thinking of creating a markdown with all the points and examples.
And create a jupyter notebook with all the code examples...
Can i do like this??

**Comment by Rishit-dagli** [comment]
> Is it okay?? i was thinking of creating a markdown with all the points and examples.
> And create a jupyter notebook with all the code examples...
> Can i do like this??

Yeah that would work!

**Comment by reddymahendra52** [comment]
I have created the PR #88 
If you feel its good I can make  another md and jupyter notebook for python variables and datatypes for training modules 
01 Introduction...

**Comment by Shashank-N-S** [comment]
can you assign this to me , i can make it as easy and simple for learners

**Comment by Rishit-dagli** [comment]
> can you assign this to me , i can make it as easy and simple for learners

@Shashank-N-S A PR addressing this has been made #88 please take a look at that, if you could add something apart of that you are welcome to create a PR.

**Comment by Rishit-dagli** [comment]
Closed via #88
